services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        tty: true
        depends_on:
            - mysql
        ports:
            - '80:80'
        volumes:
            - ../:/var/www
        working_dir: /var/www

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        expose:
            - '3306'

    phpmyadmin:
        image: phpmyadmin:5.2-apache
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
        restart: always
        ports:
            - '8080:80'
