services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        ports:
            - 3306:3306

    php:
        image: php:8.3-apache
        tty: true
        depends_on:
            - mysql
        ports:
            - 8080:80
        volumes:
            - ../:/var/www
        working_dir: /var/www

    phpmyadmin:
        image: phpmyadmin:5.2-apache
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
        restart: always
        ports:
            - 8000:80
